[project]
name = "datamole"
version = "0.1.0"
description = "This project is a FastAPI-based application that fetches events from the GitHub API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]
